### ISSUE TITLE
Project Checkpoint 1

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [agujaIvan/guestCheckInWebApp#1]
Hi Ivan, this is a reminder to let me know when you have completed the first checkpoint:

- [x] Problem statement and proposed solution
- [x] Time log/journal
- [x] Project plan
- [x] Screen design
- [x] List of technologies, independent research topic, web service/api

**Comment by agujaIvan** [comment]
I have updated this items, we should be good on this point
