### ISSUE TITLE
Instructor Review - Checkpoint 1

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [agujaIvan/guestCheckInWebApp#2]
Looks like you have a good start now!

A few things:
- [x] Remove the database design which does not pertain to your project
- [x] What will your independent research topic be?
- [x] What will your web service/api be?
- [x] Do you plan to use any css framework or will you use custom css
- [x] Elaborate the schedule - at minimum, review project checkpoints 2 and 3 and add tasks appropriately to ensure you hit those targets. Also review the course calendar and add in when you plan to choose and implement your web service/api and independent research topic.

**Comment by agujaIvan** [comment]
I have added this info, thank you again.
